name: CLI Reachability Linux

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: pnpm/action-setup@v4
      with:
        version: 10
    
    - name: build with pnpm
      run: pnpm install

    - name: Mend CLI Scan
      env:
        MEND_EMAIL: ${{secrets.MEND_SAAS_EMAIL}}
        MEND_USER_KEY: ${{secrets.MEND_SAAS_USER_KEY}}
        MEND_URL: https://saas.whitesourcesoftware.com
        MEND_DEBUG_SHOW_VERSION: true
        MEND_LOG_LEVEL: debug
      run: |
        echo Downloading Mend CLI
        curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend
        echo run Mend dependencies scan
        pwd
        ls -la
        mend update
        mend version
        mend dep -u -r --print-to-console
